[package]
name = "day-06"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.17.9"
nom = "7.1.3"

[lib]
name = "answer"
path = "src/lib.rs"
